FROM node:18-alpine as node
WORKDIR /src

#Copy Files
COPY ["P7Internet.Frontend/", "P7Internet.Frontend/"]
WORKDIR P7Internet.Frontend/react-app/

RUN pwd && ls

# RUN npm install

RUN npm run build

#Copy files from GitHub to nginx container
FROM nginx:latest

COPY --from=node build/ /usr/share/nginx/html

CMD ["npm", "start"]
