FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /src

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y \
        nodejs \
    && rm -rf /var/lib/apt/lists/*

    
#Copy Files
COPY ["P7Internet.Frontend/", "P7Internet.Frontend/"]

# Shared project

# Api project
WORKDIR /src/ASP.NETCoreWebApplication1
RUN dotnet build "P7Internet.Frontend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "P7Internet.Frontend.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /src
COPY --from=build-env /app/publish .
ENTRYPOINT ["dotnet", "P7Internet.Frontend.dll"]