FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

WORKDIR /src
COPY ["NuGet.Config","."]
COPY ["P7Internet.RestApi/P7Internet.RestApi.csproj", "P7Internet.RestApi/"]
COPY ["P7Internet.Persistence/P7Internet.Persistence.csproj", "P7Internet.Persistence/"]

# Persistence project
WORKDIR /src/P7Internet.Persistence
RUN dotnet restore
RUN dotnet build \

# Shared project

# Api project
WORKDIR /src/P7Internet.RestApi
RUN dotnet restore
RUN dotnet publish -c Release -o out


# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/Translation.RestApi/out .
ENTRYPOINT ["dotnet", "P7Internet.RestApi.dll"]
