version: '3'
services:
  dbup:
    build:
      context: .
      dockerfile: P7Internet.DbUp/Dockerfile-DbUp
  
  restapi:
    build:
      context: .
      dockerfile: P7Internet.RestApi/Dockerfile-RestApi