START TRANSACTION;

CREATE TABLE IF NOT EXISTS CachedRecipes 
(
    No          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Id          VARCHAR(250) NOT NULL,
    Recipe      LONGTEXT NOT NULL
);
CREATE INDEX CachedRecipes_Name ON CachedRecipes(Id);

COMMIT;