FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy files
COPY ["NuGet.Config", "."]
COPY ["P7Internet.DbUp/", "P7Internet.DbUp/"]

WORKDIR /src/P7Internet.DbUp
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/Translation.DbUp/out .
ENTRYPOINT ["dotnet", "P7Internet.DbUp.dll"]
