FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /src

# Copy files
COPY ["P7Internet.DbUp/", "P7Internet.DbUp/"]

WORKDIR /src/P7Internet.DbUp
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /src
COPY --from=build-env /src/P7Internet.DbUp/out .
ENTRYPOINT ["dotnet", "P7Internet.DbUp.dll"]
